In [2]:
! pip install numpy

In [3]:
import numpy as np

In [4]:
a = np.array([1, 2, 3, 4, 5])

In [5]:
a

array([1, 2, 3, 4, 5])

In [7]:
a + 10

array([11, 12, 13, 14, 15])

In [10]:
b = a * 10
b

array([10, 20, 30, 40, 50])

In [11]:
a + b

array([11, 22, 33, 44, 55])

In [12]:
a * b

array([ 10,  40,  90, 160, 250])

In [41]:
b.sum()

150

In [15]:
np.arange(3, 10, 0.5)

array([3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. , 7.5, 8. , 8.5, 9. ,
       9.5])

In [17]:
np.zeros(6), np.ones(6)

(array([0., 0., 0., 0., 0., 0.]), array([1., 1., 1., 1., 1., 1.]))

In [19]:
c = np.array([[1, 2, 3], [3, 4, 5], [6, 7, 8]])
c

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]])

In [28]:
c[0, 1] = 200
c

array([[  1, 200,   3],
       [  3,   4,   5],
       [  6,   7,   8]])

In [30]:
c[0:2, 1:3] = 99
c

array([[ 1, 99, 99],
       [ 3, 99, 99],
       [ 6,  7,  8]])

In [49]:
c + 100

array([[101, 199, 199],
       [103, 199, 199],
       [106, 107, 108]])

In [50]:
c * np.array([[0, 1, 0], [1, 1000, 1], [0, 1, 0]])

array([[    0,    99,     0],
       [    3, 99000,    99],
       [    0,     7,     0]])

In [34]:
np.arange(100).shape

(100,)

In [36]:
d = np.arange(100).reshape(10, 10)
d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [37]:
d.shape

(10, 10)

In [43]:
d.sum()

4950

In [46]:
d.sum(axis=0, keepdims=True)

array([[450, 460, 470, 480, 490, 500, 510, 520, 530, 540]])

In [47]:
d.sum(axis=1, keepdims=True)

array([[ 45],
       [145],
       [245],
       [345],
       [445],
       [545],
       [645],
       [745],
       [845],
       [945]])

In [57]:
np.arange(5) * np.array([0, 0, 1, 0, 0]).reshape(5, 1)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 1, 2, 3, 4],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])